import React from 'react'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
    <div className="container mx-auto flex justify-between items-center">
        <div className="text-white text-3xl font-bold">🐘 JUMBO DUMBO</div>
        <div className="hidden md:flex space-x-4">
            <a href="about" className="text-gray-300 hover:text-white">About</a>
            <a href="gallery" className="text-gray-300 hover:text-white">Gallery</a>
            <a href="diet" className="block text-gray-300 hover:text-white">Diet</a>
            <a href="popculture" className="block text-gray-300 hover:text-white">Pop Culture</a>
            <a href="communication" className="block text-gray-300 hover:text-white">Communication</a>
        </div>
        <div className="md:hidden">
            <button id="navbar-toggle" className="text-gray-300 focus:outline-none">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16m-7 6h7"></path>
                </svg>
            </button>
        </div>
    </div>
    <div id="navbar-menu" className="hidden md:hidden">
        <a href="about" className="block text-gray-300 hover:text-white">About</a>
        <a href="gallery" className="block text-gray-300 hover:text-white">Gallery</a>
        <a href="popculture" className="block text-gray-300 hover:text-white">Pop Culture</a>
        <a href="communication" className="block text-gray-300 hover:text-white">Communication</a>
    </div>
</nav>
        {children}
      </body>
    </html>
  );
}
